refactor: modularization
hldb/welo pull request #71
Opened 2023-05-24 05:40 UTC by saul-jb

This PR is a work in progress example of refactoring the registrar into a more modular design.

I envision the end API to look something like:
```javascript
import { createWelo } from 'welo'
import { liveReplicator } from 'welo/replicator/live'
import { basalEntry, createBasalEntryConfig } from 'welo/entry/basal'
import { basalIdentity, createBasalIdentityConfig } from 'welo/identity/basal'
import { staticAccess, createStaticAccessConfig } from 'welo/access/static'
import { keyvalue, createKeyvalueConfig } from 'welo/store/keyvalue'

const welo = await createWelo({
  helia,
  dir: './welo',
  datastore: LevelDatastore,
  replicators: [ liveReplicator() ],
  identities: [ basalIdentity() ],
  entries: [ basalEntry() ],
  access: [ staticAccess() ]
})

const manifest = await welo.determine({
  name: "my-database",
  access: createStaticAccessConfig({ write: ['*'] }),
  entry: createBasalEntryConfig(),
  store: createKeyvalueConfig(),
  identity: createBasalIdentityConfig()
})

const db = await welo.open(manifest)
const store = await keyvalue(db)
```

2023-05-24 13:38 UTC, tabcat commented on src/entry/interface.ts
> +import { OPALSNT_PREFIX } from '@/utils/constants.js'
This variable needs to be changed to `HLDB_PREFIX` in constants.js. I thought I had done this already. Feel free to do it as part of this PR or I can do it after merging.

2023-05-24 14:06 UTC, tabcat reviewed
Loving the changes so far :+1: 

:crab: registry gone :crab: 

These will require a major version bump so add a ! to the end of refactor or I can do that when merging

2023-05-24 15:54 UTC, tabcat commented on src/utils/index.ts
> +  Identity
Can add this later

2023-05-25 03:31 UTC, saul-jb commented on src/entry/interface.ts
> +import { OPALSNT_PREFIX } from '@/utils/constants.js'
Alright, I've added the change to this fork.

2023-05-25 03:33 UTC, saul-jb commented on src/utils/index.ts
> +  Identity
This has now been fixed, there was (and still is) some things I have just modified solely for the tests to pass while I am changing other things.

2023-05-25 03:36 UTC, saul-jb commented on src/utils/index.ts
> +    protocol: Identity.protocol
I have added this change, which should also help make the manifest creation code shorter.

2023-05-25 03:43 UTC, saul-jb commented
Register is now completely gone along with the multi-replicator. More changes to come.

2023-05-27 06:40 UTC, saul-jb commented
Unfortunately this has become a 'rewrite the entire codebase' PR, so apologies for that, it should have probably been split into a few PRs.

Major changes:
- Register has been removed.
- Multi-replication is the default and multi-replicator removed.
- Modules have been refactored for a more modular design.
- Level-datastores have been replaced with namespaced datastore instances.
- Static modules have been replaced module instances.
- Types have been cleaned up a bit.

Marking this as ready but will need reviewing to ensure that functionality remains the same.

2023-05-27 17:07 UTC, tabcat requested changes
Looking really good :fire: :+1: :100: just a few (relative) things to talk about

Love the use of `NamespaceDatastore` !!

wondering if we could use the helia data/block -stores (by default) if they are name spaced

Feel free to choose address some of the comments in a new PR, fine merging everything as is

A change I'm thinking about has to do with making it so `identityModule` can be just `identity` inside `database.modules` or `database.components` and `database.identity` can become `database.writer` to be sure there is no confusion (this is for a future PR one of us makes)

Also would like to (in the near future) make creating a welo instance simpler and show that in the usage, helia just did a default helia config for createHelia that does this (for reference)

2023-05-29 00:10 UTC, saul-jb commented
> wondering if we could use the helia data/block -stores (by default) if they are name spaced

I suspect this is a bad idea since Helia would be expecting exclusive access to the store, instead I used the in-memory store as the default (like Helia does) and if the user wants to use the same store for both they can pass unique namespaces to both Welo and Helia.

2023-05-29 01:44 UTC, merged